### ISSUE TITLE
Download Error - 403 when trying to download from https://get.pulumi.com/releases/plugins/pulumi-resource-talos-v0.2.0-linux-amd64.tar.gz

### ISSUE THREAD

**Issue by muhlba91** [pulumiverse/pulumi-talos#102]
Since a couple of days I got sporadic errors that downloading the provider doesn't work with the same error happening now all the time. It looks like Pulumi doesn't pick GitHub to download the provider but goes straight to Pulumi.

Is this related to this provider, a regression of Pulumi itself or anything else?

The error I receive is:
```
error: could not load provider for resource urn:pulumi:prod::home_cluster-infrastructure-proxmox::talos:machine/secrets:Secrets::talos-secrets-rev2: could not create provider urn:pulumi:prod::home_cluster-infrastructure-proxmox::pulumi:providers:talos::default_0_2_0_***_/api.***.com/pulumiverse::a4e8abad-3043-497d-82e1-85aa4ace9939: load plugin for talos provider 'urn:pulumi:prod::home_cluster-infrastructure-proxmox::pulumi:providers:talos::default_0_2_0_***_/api.***.com/pulumiverse': Could not automatically download and install resource plugin 'pulumi-resource-talos' at version v0.2.0, install the plugin using `pulumi plugin install resource talos v0.2.0`: error downloading provider talos to file: failed to download plugin: talos-0.2.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-talos-v0.2.0-linux-amd64.tar.gz
```

**Comment by ringods** [comment]
@muhlba91 Pulumi will fallback to `get.pulumi.com` to download when the configured `pluginDownloadUrl` errors out.

Is it possible you are getting rate limited by Github? If you don't have a `GITHUB_TOKEN` set, can you try setting one? Pulumi detects this env variable and passes the token for any download to Github. The usage of a token changes the rate limits from anonymous (low api rate limits) to authenticated downloads (with higher api rate limits)

**Comment by muhlba91** [comment]
this is good to know that there's a fallback.

anhow, this also happens in GitHub actions and setting the token doesn't change anything.
usage of the actions token: https://github.com/muhlba91/homelab-kubernetes-home-infrastructure/actions/runs/10301434225/job/28513058386#step:10:87
usage of a private access token: https://github.com/muhlba91/homelab-kubernetes-home-infrastructure/actions/runs/10297098715/job/28499597833#step:10:86

**Comment by ringods** [comment]
@muhlba91 does this problem still persist for you?

**Comment by muhlba91** [comment]
it started working again - sorry for forgetting to close this issue.
