### ISSUE TITLE
Cannot add root certificate to control plane machine

### ISSUE THREAD

**Issue by stenzing** [pulumiverse/pulumi-talos#106]
I have a talos cluster of 1 cp node and 3 workers. On the cluster there is a keycloak service running +externaldns is configured for the network to register the dns names. There is a ca cert created for the services for the .localcluster zone, and the keycloak has its own certificate signed by the root cert.
After setting up OIDC for user authentication via the following patch:
`cluster:

    apiServer:

        extraArgs:

            authorization-mode: Node,RBAC

            oidc-client-id: k8s

            oidc-groups-claim: groups

            oidc-groups-prefix: ""

            oidc-issuer-url: https://keycloak.homelab.localcluster/realms/Homelab

            oidc-username-claim: name

            oidc-username-prefix: '-'
`

and adding the certificate based on this docs: https://www.talos.dev/v1.8/talos-guides/configuration/certificate-authorities/#appending-the-certificate-authority and aapplying the file as:
`talosctl patch mc --nodes 192.168.1.220 -e 192.168.1.220  --patch @localcluster-ca.yaml`

I still see the following error in the apiserver logs: 
`stderr F E1016 08:58:34.699336       1 oidc.go:383] oidc authenticator: initializing plugin: Get "https://keycloak.homelab.localcluster/realms/Homelab/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority`

seems that not even a restart helps to get the root certificate to be added as trusted.
Any other way to enrich the machine setup with the root cert? On my other nodes, where I run traditional linux machines installing the root cert to be trusted solved the issue.

**Comment by UnstoppableMango** [comment]
Given you're applying the patch with `talosctl`, it sounds like your issue has more to do with Talos than the Pulumi provider here. I think you'll find people more equipped to help over at https://github.com/siderolabs/talos

The Pulumi provider does allow providing patches, so if you have something that works with `talosctl` but doesn't work with the Pulumi provider, please let us know!

**Comment by ringods** [comment]
@stenzing this indeed looks more like a Talos specific question. This repository is about the managing your Talos cluster using the [Pulumi](https://www.pulumi.com) Infrastructure As Code solution.

You can find the Talos Community information here: https://github.com/siderolabs/talos?tab=readme-ov-file#community
