### ISSUE TITLE
Make a new release with changes to support Talos v1.8.x

### ISSUE THREAD

**Issue by shkarface** [pulumiverse/pulumi-talos#107]

**Comment by shkarface** [comment]
@UnstoppableMango anything we can do about this new release?

**Comment by UnstoppableMango** [comment]
Hey @shkarface sorry for the delayed response, I attempted to update the provider a week or two back and ran into issues. The error messages talked about an unsupported feature in Pulumi, but I haven't had a chance yet to dig further. I'll try to get time this week to work on a new release!

I'd also like to see Talos 1.8.x working as I need some features offered by it to implement [integration tests](https://github.com/pulumiverse/pulumi-talos/pull/88). I'm hoping that once we get the Pulumi kinks worked out and tests running in CI we make iterate faster in this repo!

**Comment by shkarface** [comment]
Thank you @UnstoppableMango, I also tried the local pulumi SDK generation but had some issues with it, I think @ringods is working on some changes currently

**Comment by ringods** [comment]
@shkarface v0.4.1 is currently building. This brings the provider in sync with the upstream TF provider v0.6.1

https://github.com/pulumiverse/pulumi-talos/releases/tag/v0.4.1

**Comment by shkarface** [comment]
Thanks for the timely response @ringods, I will upgrade my envs tomorrow using this new version

**Comment by ringods** [comment]
@shkarface the provider has been upgraded on a technical basis to the latest TF version, but no testing has been done on it. Please file new issues when you bump into problems. 🙏🏻
