### ISSUE TITLE
add back some of the SDK languages

### ISSUE THREAD

**Issue by TECHNOFAB11** [pulumiverse/pulumi-talos#25]
Pulumi supports a bunch of languages to define the infrastructure and it would be nice if this provider would support more languages than just Go (which is not ideal for defining configuration/infra). 
Especially NodeJS would be nice to have, as it is the easiest to read quickly imo. 
Is it possible for siderolabs to publish an official npm package as generating it with build_nodejs works fine?

And thanks a lot for the work on Talos, it's amazing :)

**Comment by frezbo** [comment]
We don't have this currently in the plans, PR's are welcome if this is an easy fix to use github to host the npm packages

**Comment by oliverwiegers** [comment]
Hello together,
I was about to start on this but it seems parts are already done in #26

**Comment by ringods** [comment]
This provider is now maintained by the community. The first correct release is published as v0.1.3:

* NodeJS: https://www.npmjs.com/package/@pulumiverse/talos
* Python: https://pypi.org/project/pulumiverse-talos/
* Go: https://github.com/pulumiverse/pulumi-talos/tree/main/sdk/go
* .NET: https://www.nuget.org/packages/Pulumiverse.Talos
