### ISSUE TITLE
Provider not present in the pulumi registry

### ISSUE THREAD

**Issue by oliverwiegers** [pulumiverse/pulumi-talos#31]
Hello together,

thank you for your work :)

The Readme references the the [pulumi registry](https://www.pulumi.com/registry/packages/talos/api-docs/) to look at the API docs.
Unfortunately the Talos provider is not present in the pulumi registry (anymore).

Are you aware? If yes will the package be back in the registry?

**Comment by hawkkiller** [comment]
Hey! This issue still persists.

**Comment by maxromanovsky** [comment]
Any news, or is it discontinued?

**Comment by UnstoppableMango** [comment]
[Reply from a maintainer](https://github.com/siderolabs/pulumi-provider-talos/issues/43#issuecomment-1764200679) for those that may have missed it.

I plan to start a fork, but no guarantees on how much time I'll be able to devote to maintaining it

**Comment by ringods** [comment]
@UnstoppableMango as board member of [Pulumiverse](https://github.com/pulumiverse), I can inform you that the provider will move to this community. I hope we can count on your contributions there.

Give us a bit of time to have the transfer of this repo to be done. 🙏🏻

**Comment by ringods** [comment]
Here is the request to have this provider added to the Pulumi Registry:

https://github.com/pulumi/registry/pull/3367

**Comment by ringods** [comment]
And we are live!

https://www.pulumi.com/registry/packages/talos/
