### ISSUE TITLE
Talos 1.5.0 compatibility

### ISSUE THREAD

**Issue by JuYo26** [pulumiverse/pulumi-talos#40]
Hello !
Talos 1.5.0 has just been released and it seems to introduce some breaking changes in the Talos configuration. Is it planned to upgrade this pulumi provider or this project is dead ?
Thanks !

**Comment by ringods** [comment]
Version [0.1.4](https://github.com/pulumiverse/pulumi-talos/releases/tag/v0.1.4) of the provider has been built against Talos TF provider v0.3.4, which supports the latest Talos v1.5.0.
