### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by Sacro** [pulumiverse/pulumi-talos#60]
Given this is a terraform wrapper, should it not be pulumi-tf-talos?

**Comment by UnstoppableMango** [comment]
The naming guidelines from the [Pulumi documentation](https://www.pulumi.com/docs/using-pulumi/pulumi-packages/how-to-author/#name-your-repository) specify:

> If you’re naming a bridged provider, re-use the Terraform provider’s name but replace the `terraform-provider-` prefix with `pulumi-`

So given that the [source repository](https://github.com/siderolabs/terraform-provider-talos/) is named `terraform-provider-talos`, it would follow that this repo should be named `pulumi-talos`.

**Comment by Sacro** [comment]
Apologies, I must have misread it.

**Comment by Sacro** [comment]
Closed
